gcloud alpha compute tpus tpu-vm ssh yizhongwang@yizhong-tpu-v3-256-1 --ssh-key-file ~/.ssh/google_compute_engine --zone=us-east1-d --project=ai2-tpu --worker=all --command="cd EasyLM; git pull origin ppo; export LIBTPU_INIT_ARGS='--xla_jf_spmd_threshold_for_windowed_einsum_mib=0 --xla_tpu_spmd_threshold_for_allgather_cse=10000 --xla_tpu_spmd_rewrite_einsum_with_reshape=true --xla_tpu_enable_latency_hiding_scheduler=true TPU_MEGACORE=MEGACORE_DENSE'; python3 -m EasyLM.models.llama.llama_train_ppo \
    --mesh_dim='1,64,4' \
    --load_llama_config_policy='13b' \
    --load_llama_config_reward='13b' \
    --load_checkpoint_policy='params::gs://hamishi-east1/easylm/llama2/tulu2_13b_fixed/tulu2_13b_fixed/455af914503740be9664497dae996762/streaming_params' \
    --load_checkpoint_reward='params::gs://hamishi-east1/tulu2_13b_ultrafeedback_rm/7371c411dcfd4b09994aaa50a3a07128/streaming_params_1903' \
    --tokenizer.vocab_file='gs://jiachengl-east1/tokenizer.model' \
    --tokenizer.add_bos_token=True \
    --train_dataset.type='tulu_prompt' \
    --train_dataset.tulu_prompt_dataset.path='/home/yizhongwang/data/ultrafeedback_mean_aspects_cleaned.jsonl' \
    --train_dataset.tulu_prompt_dataset.seq_length=1024 \
    --max_continuation_len=1024 \
    --train_dataset.tulu_prompt_dataset.batch_size=64 \
    --mini_batch_size=64 \
    --train_dataset.tulu_prompt_dataset.num_workers=16 \
    --train_dataset.tulu_prompt_dataset.remove_truncated_samples=True \
    --optimizer.type='adamw' \
    --optimizer.adamw_optimizer.weight_decay=0.0 \
    --optimizer.adamw_optimizer.warmup_ratio=0.1 \
    --checkpointer.save_optimizer_state=False \
    --logger.online=True \
    --logger.entity='yizhongw' \
    --logger.project='tulu2.5' \
    --logger.prefix='train_v2.2_v2.1_llama-13b-base-rm-uf-only' \
    --logger.prefix_to_id=True \
    --logger.wandb_dir='/home/yizhongwang/wandb/' \
    --logger.output_dir='gs://yizhong-east1/tulu2.5/ppo' \
    --use_tpu=True \
    --ppo_epochs=1 \
    --lr=1e-6 \
    --kl_coef=0.05 \
    --reward_gain=1.0 --reward_bias=0.0 \
    --save_milestone_freq=100 \
    --num_epochs=1 \
    --max_steps_per_epoch=0 \
    --generate_only=False \
    &> /home/yizhongwang/logs/test.log &"
